"""Explicit database operations. Never imported or invoked by application boot.

Run `python -m server.manage_db --help`. SQLite input is opened read-only.
Import DDL, records, verification, indexes and completion ledger commit together.
"""
import argparse
from contextlib import closing
import hashlib
import json
import os
from pathlib import Path
import re
import sqlite3
import sys
import tempfile
import time

import psycopg

from server.schema import SCHEMA, SCHEMA_VERSION, INDEXES, TABLES, REQUIRED_COLUMNS
from server.reference_data import CATEGORIES, PROVINCES, BRANDS, DEFAULT_SETTINGS

LOCK_ID = 1279348293
LEDGER = "ll_schema_migrations"
LEDGER_DDL = f"""CREATE TABLE IF NOT EXISTS {LEDGER} (
    version INTEGER PRIMARY KEY,
    source_sha256 TEXT NOT NULL,
    manifest TEXT NOT NULL,
    applied_at BIGINT NOT NULL
)"""


class MigrationError(RuntimeError):
    """Only controlled, non-sensitive messages may be printed to the operator."""


def identifier(name):
    return '"' + name.replace('"', '""') + '"'


def source_connection(path):
    path = Path(path).resolve(strict=True)
    conn = sqlite3.connect(path.as_uri() + "?mode=ro", uri=True)
    conn.execute("PRAGMA query_only = ON")
    return conn


def snapshot(source, destination):
    """SQLite backup API includes committed WAL data; never copy only the .db file."""
    destination = Path(destination)
    fd = os.open(destination, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
    os.close(fd)
    with closing(source_connection(source)) as src, closing(sqlite3.connect(destination)) as dst:
        src.backup(dst)
        if dst.execute("PRAGMA integrity_check").fetchone()[0] != "ok":
            raise MigrationError("SQLite integrity check failed; do not cut over")
    return destination


def fingerprint(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def statements(script):
    buffer = ""
    for line in script.splitlines(True):
        buffer += line
        if sqlite3.complete_statement(buffer):
            yield buffer.strip()
            buffer = ""
    if buffer.strip():
        raise MigrationError("Incomplete schema statement; manual schema review required")


def schema_info(conn):
    result = {}
    for name, ddl in conn.execute("SELECT name, sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"):
        if name == LEDGER:
            continue
        result[name] = {
            "ddl": ddl,
            "columns": list(conn.execute(f"PRAGMA table_info({identifier(name)})")),
            "foreign_keys": list(conn.execute(f"PRAGMA foreign_key_list({identifier(name)})")),
        }
    return result


def inspect_source(conn):
    if conn.execute("PRAGMA integrity_check").fetchone()[0] != "ok":
        raise MigrationError("SQLite integrity check failed")
    if conn.execute("PRAGMA foreign_key_check").fetchone():
        raise MigrationError("SQLite has orphaned foreign keys; reconcile them without deleting data before import")
    if conn.execute("SELECT 1 FROM sqlite_master WHERE type IN ('trigger','view') LIMIT 1").fetchone():
        raise MigrationError("Source has triggers/views; explicit PostgreSQL translations are required before import")
    info = schema_info(conn)
    if not info:
        raise MigrationError("Source contains no application tables; refusing an empty migration")
    if not {"users", "listings"} <= set(info) or not conn.execute("SELECT 1 FROM users LIMIT 1").fetchone():
        raise MigrationError("Source lacks marketplace accounts/core tables; verify the correct live backup instead of importing an empty marketplace")
    for item in info.values():
        if re.search(r"\b(VIRTUAL|GENERATED|COLLATE|WITHOUT\s+ROWID)\b", item["ddl"], re.I):
            raise MigrationError("Source has non-portable schema features; manual review required")
    return info


def canonical_info():
    with closing(sqlite3.connect(":memory:")) as conn:
        conn.executescript(SCHEMA)
        return schema_info(conn)


def ddl_postgres(ddl):
    # Only trusted schema from the operator's backup is accepted. Quoted defaults
    # (including names containing SQL keywords) must remain byte-for-byte intact.
    parts = re.split(r"('(?:''|[^'])*'|\"(?:\"\"|[^\"])*\"|--[^\n]*)", ddl)
    for i in range(0, len(parts), 2):
        part = re.sub(r"\bINTEGER\s+PRIMARY\s+KEY(?:\s+AUTOINCREMENT)?", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", parts[i], flags=re.I)
        part = re.sub(r"\bINTEGER\b", "BIGINT", part, flags=re.I)
        part = re.sub(r"\bBLOB\b", "BYTEA", part, flags=re.I)
        part = re.sub(r"\bREAL\b", "DOUBLE PRECISION", part, flags=re.I)
        parts[i] = part
    ddl = "".join(parts)
    # Source FKs may be immediate. Deferral permits preserving arbitrary row
    # ordering, including self-referencing categories; validation still occurs
    # before commit. Table creation itself is dependency ordered below.
    ddl = re.sub(r'(REFERENCES\s+(?:"[^"]+"|\w+)\s*\([^)]*\)(?:\s+ON\s+DELETE\s+(?:CASCADE|RESTRICT|NO ACTION|SET NULL|SET DEFAULT))?)(?!\s+DEFERRABLE)',
                 r'\1 DEFERRABLE INITIALLY IMMEDIATE', ddl, flags=re.I)
    return ddl


def table_order(info):
    done, pending, ordered = set(), set(info), []
    while pending:
        available = sorted(t for t in pending if {r[2] for r in info[t]["foreign_keys"] if r[2] != t} <= done)
        if not available:
            raise MigrationError("Cyclic or missing table dependencies require an explicit migration; no data imported")
        for name in available:
            done.add(name)
            pending.remove(name)
            ordered.append(name)
    return ordered


def pg_url():
    url = os.getenv("DATABASE_URL", "").strip()
    if not url.startswith(("postgresql://", "postgres://")):
        raise MigrationError("Set DATABASE_URL to the destination PostgreSQL service using environment variables")
    return url


def pg_connect():
    return psycopg.connect(pg_url(), connect_timeout=10,
                          options="-c search_path=public -c lock_timeout=10000")


def lock(conn):
    conn.execute("SELECT pg_advisory_xact_lock(%s)", (LOCK_ID,))


def destination_tables(conn):
    return {r[0] for r in conn.execute("SELECT tablename FROM pg_tables WHERE schemaname = 'public'")}


def row_digest(rows):
    # Order-independent, duplicate-sensitive multiset digest, bounded memory.
    # Encodes types too, so a lossy SQLite affinity conversion aborts the import.
    total = xor = count = 0
    for row in rows:
        values = []
        for value in row:
            if isinstance(value, (bytes, memoryview)):
                values.append(["bytes", bytes(value).hex()])
            else:
                values.append([type(value).__name__, value])
        digest = int.from_bytes(hashlib.sha256(json.dumps(values, ensure_ascii=False, separators=(",", ":")).encode()).digest(), "big")
        total = (total + digest) % (1 << 256)
        xor ^= digest
        count += 1
    return {"count": count, "sum_sha256": f"{total:064x}", "xor_sha256": f"{xor:064x}"}


def verify_rows(src, pg, info):
    manifest = {}
    for name, item in info.items():
        cols = ",".join(identifier(c[1]) for c in item["columns"])
        statement = f"SELECT {cols} FROM {identifier(name)}"
        source_hash = row_digest(src.execute(statement))
        with pg.cursor(name="verify_rows") as cur:
            cur.execute(statement)
            dest_hash = row_digest(cur)
        if source_hash != dest_hash:
            raise MigrationError("Row verification mismatch; entire import rolled back")
        manifest[name] = source_hash
    return manifest


def add_missing_columns_pg(conn, info):
    """Only additive baseline upgrades. Never overwrite an existing source cell."""
    added = {}
    for name, canonical in canonical_info().items():
        present = {c[1] for c in info[name]["columns"]}
        for col in canonical["columns"]:
            if col[1] in present:
                continue
            if col[5] or (col[3] and col[4] is None):
                raise MigrationError("Legacy schema lacks a required key/column; manual additive migration required")
            declaration = f"{identifier(col[1])} {col[2]}"
            if col[4] is not None:
                declaration += " DEFAULT " + col[4]
            conn.execute(f"ALTER TABLE {identifier(name)} ADD COLUMN {ddl_postgres(declaration)}")
            added.setdefault(name, set()).add(col[1])
    return added


def backfill_new_columns(conn, added, placeholder="%s"):
    # These cells did not exist in SQLite. Existing statuses/expiries are never changed.
    if "expires_at" in added.get("sessions", set()):
        conn.execute(f"UPDATE sessions SET expires_at = created_at + {placeholder}", (30 * 86400,))
    if "verification_status" in added.get("businesses", set()):
        conn.execute("UPDATE businesses SET verification_status = 'approved' WHERE verified = 1")
    for col in ("submitted_at", "reviewed_at"):
        if col in added.get("businesses", set()):
            conn.execute(f"UPDATE businesses SET {col} = COALESCE(created_at, 0) WHERE verification_status = 'approved'")


def reset_sequences(conn, src, info):
    sequences = dict(src.execute("SELECT name, seq FROM sqlite_sequence")) if src.execute("SELECT 1 FROM sqlite_master WHERE name='sqlite_sequence'").fetchone() else {}
    for name, item in info.items():
        for col in item["columns"]:
            seq = conn.execute("SELECT pg_get_serial_sequence(%s, %s)", (identifier(name), col[1])).fetchone()[0]
            if seq:
                maximum = conn.execute(f"SELECT MAX({identifier(col[1])}) FROM {identifier(name)}").fetchone()[0] or 0
                high = max(maximum, sequences.get(name, 0), 0)
                conn.execute("SELECT setval(%s::regclass, %s, %s)", (seq, max(1, high), high > 0))


def import_sqlite(source):
    # Re-snapshot even an uploaded backup, so any WAL pages are included and the
    # migration reads a stable image. The live source is always read-only.
    with tempfile.TemporaryDirectory(prefix="ll-migration-") as tmp:
        copy = snapshot(source, Path(tmp) / "source.sqlite3")
        digest = fingerprint(copy)
        with closing(source_connection(copy)) as src, pg_connect() as pg:
            info = inspect_source(src)
            lock(pg)
            tables = destination_tables(pg)
            if LEDGER in tables:
                prior = pg.execute(f"SELECT source_sha256 FROM {LEDGER} WHERE version = %s", (SCHEMA_VERSION,)).fetchone()
                if prior and prior[0] == digest:
                    # Idempotent after cutover: do not rewind data changed since import.
                    print("This exact SQLite snapshot was already imported; no records changed.")
                    return
            if tables:
                raise MigrationError("Destination public schema is not empty; refusing to merge, overwrite, or delete records")
            merged = canonical_info()
            merged.update(info)
            for name in table_order(merged):
                pg.execute(ddl_postgres(merged[name]["ddl"]))
            added = add_missing_columns_pg(pg, merged)
            pg.execute("SET CONSTRAINTS ALL DEFERRED")
            for name in table_order(merged):
                if name not in info:
                    continue
                columns = [c[1] for c in info[name]["columns"]]
                col_sql = ",".join(identifier(c) for c in columns)
                # Text COPY adapts Python types correctly and is bounded-memory.
                with pg.cursor() as cur:
                    with cur.copy(f"COPY {identifier(name)} ({col_sql}) FROM STDIN") as writer:
                        for row in src.execute(f"SELECT {col_sql} FROM {identifier(name)}"):
                            writer.write_row(row)
            manifest = verify_rows(src, pg, info)
            backfill_new_columns(pg, added)
            reset_sequences(pg, src, merged)
            # Flush deferred FK trigger events before building indexes. Any
            # orphan still aborts the entire transaction (including all DDL).
            pg.execute("SET CONSTRAINTS ALL IMMEDIATE")
            # Keep all explicit source indexes, including extra legacy indexes.
            for (ddl,) in src.execute("SELECT sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL ORDER BY name"):
                pg.execute(ddl_postgres(ddl))
            for ddl in INDEXES:
                pg.execute(ddl)
            pg.execute("SET CONSTRAINTS ALL IMMEDIATE")
            pg.execute(LEDGER_DDL)
            pg.execute(f"INSERT INTO {LEDGER} VALUES (%s,%s,%s,%s)",
                       (SCHEMA_VERSION, digest, json.dumps(manifest, sort_keys=True), int(time.time())))
        # Printed only after the context manager successfully committed.
        print("Import committed. Every original table/column value verified; IDs and sequence high-water marks preserved.")
        print(json.dumps({name: item["count"] for name, item in manifest.items()}, sort_keys=True))


def insert_reference(conn, pg):
    def write(statement, args):
        return conn.execute(statement.replace("?", "%s") if pg else statement, args)
    def insert_id(statement, args):
        cur = write(statement + (" RETURNING id" if pg else ""), args)
        return cur.fetchone()[0] if pg else cur.lastrowid
    ids = {}
    for slug, name, icon, parent, sort, fields in CATEGORIES:
        ids[slug] = insert_id("INSERT INTO categories (slug,name,icon,parent_id,sort,fields) VALUES (?,?,?,?,?,?)", (slug, name, icon, ids.get(parent), sort, fields))
    for pname, districts in PROVINCES.items():
        pid = insert_id("INSERT INTO provinces (name) VALUES (?)", (pname,))
        for dname, cities in districts.items():
            did = insert_id("INSERT INTO districts (province_id,name) VALUES (?,?)", (pid, dname))
            for city in cities:
                write("INSERT INTO cities (district_id,name) VALUES (?,?)", (did, city))
    for name, category in BRANDS:
        write("INSERT INTO brands (name,category) VALUES (?,?)", (name, category))
    for key, value in DEFAULT_SETTINGS.items():
        write("INSERT INTO site_settings (key,value) VALUES (?,?)", (key, str(value)))


def init_empty():
    """Prepare a BRAND-NEW database: schema, indexes, constraints, reference data.

    Explicit operator action only; application startup and pre-deploy never call
    it. PostgreSQL safety rules:

    * The destination ``public`` schema must contain no tables at all. Any
      existing table aborts the command before any DDL is issued.
    * Nothing is ever dropped or truncated and no existing row is touched; an
      aborted run rolls back completely.
    * Schema, indexes, reference data and the completion ledger commit together
      in one transaction under a transaction-scoped advisory lock.
    * Re-running on an already prepared database is a no-op that changes
      nothing and never duplicates reference rows.
    """
    url = os.getenv("DATABASE_URL", "").strip()
    if url:
        with pg_connect() as conn:
            lock(conn)
            tables = destination_tables(conn)
            if LEDGER in tables and conn.execute(f"SELECT 1 FROM {LEDGER} WHERE version=%s", (SCHEMA_VERSION,)).fetchone():
                print("Database already prepared; nothing changed.")
                return
            if tables:
                raise MigrationError(
                    "Destination public schema is not empty; init-empty only prepares a brand-new "
                    "database and never drops, truncates or overwrites existing tables")
            with conn.transaction():
                for ddl in statements(SCHEMA):
                    conn.execute(ddl_postgres(ddl))
                for ddl in INDEXES:
                    conn.execute(ddl)
                insert_reference(conn, True)
                conn.execute(LEDGER_DDL)
                conn.execute(f"INSERT INTO {LEDGER} VALUES (%s,%s,%s,%s)",
                             (SCHEMA_VERSION, "explicit-empty", "{}", int(time.time())))
    else:
        from server.database import database
        # Database config has already refused SQLite in a production environment.
        path = Path(database.sqlite_path)
        if path.exists():
            with closing(source_connection(path)) as existing:
                if existing.execute("SELECT 1 FROM sqlite_master WHERE name=?", (LEDGER,)).fetchone():
                    print("Database already prepared; nothing changed.")
                    return
            raise MigrationError("SQLite file already exists but is not prepared; it is never overwritten")
        path.parent.mkdir(parents=True, exist_ok=True)
        fd = os.open(path, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
        os.close(fd)
        with closing(sqlite3.connect(path)) as conn, conn:
            for ddl in statements(SCHEMA):
                conn.execute(ddl)
            for ddl in INDEXES:
                conn.execute(ddl)
            insert_reference(conn, False)
            conn.execute(LEDGER_DDL)
            conn.execute(f"INSERT INTO {LEDGER} VALUES (?,?,?,?)",
                         (SCHEMA_VERSION, "explicit-empty", "{}", int(time.time())))
    print("Fresh database explicitly initialized with schema, indexes and reference data only; no demo users, shops or listings.")


def migrate():
    """Version 1 is the baseline. Future reviewed additive migrations go here."""
    with pg_connect() as conn:
        lock(conn)
        if LEDGER not in destination_tables(conn):
            raise MigrationError("Database not prepared: import SQLite first (or explicitly initialize a new installation)")
        versions = {r[0] for r in conn.execute(f"SELECT version FROM {LEDGER}")}
        if versions != {SCHEMA_VERSION}:
            raise MigrationError("Unsupported schema version; deploy the matching application/migration")
        if not set(TABLES) <= destination_tables(conn):
            raise MigrationError("Database schema is incomplete; restore/reconcile from backup")
        for table, columns in REQUIRED_COLUMNS.items():
            conn.execute(f"SELECT {','.join(identifier(c) for c in columns)} FROM {identifier(table)} LIMIT 0")
    print("Schema version 1 is current; no records changed.")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    backup = sub.add_parser("backup-sqlite", help="Consistent SQLite backup, destination must not exist")
    backup.add_argument("--source", required=True)
    backup.add_argument("--output", required=True)
    imp = sub.add_parser("import-sqlite", help="Atomic import into EMPTY PostgreSQL; never run init-empty first")
    imp.add_argument("--source", required=True)
    sub.add_parser("init-empty",
                   help="Prepare a brand-NEW installation (schema, indexes, constraints, "
                        "reference data); refuses if any table already exists; never drops data")
    sub.add_parser("migrate", help="Explicit, idempotent PostgreSQL schema version check/upgrades")
    sub.add_parser("seed-demo", help="Local SQLite only; explicitly add demo accounts/listings")
    args = parser.parse_args()
    try:
        if args.command == "backup-sqlite":
            path = snapshot(args.source, args.output)
            print("Consistent backup complete. SHA256:", fingerprint(path))
        elif args.command == "import-sqlite":
            import_sqlite(args.source)
        elif args.command == "init-empty":
            init_empty()
        elif args.command == "migrate":
            migrate()
        elif args.command == "seed-demo":
            from server.database import database
            if database.production or database.is_postgres:
                raise MigrationError("Demo data is allowed only in local SQLite development")
            with closing(source_connection(database.sqlite_path)) as conn:
                if any(conn.execute(f"SELECT 1 FROM {t} LIMIT 1").fetchone() for t in ("users", "listings", "businesses", "posts")):
                    raise MigrationError("Demo seed refused: existing persistent records must not be mixed with demo data")
            from server.app import seed
            seed()
            print("Local demo data created.")
    except MigrationError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    except Exception:
        # Never print driver exceptions, SQL, connection strings or user records.
        print("Database operation failed; no successful migration reported. Check connectivity, schema compatibility and backup integrity. No source records were changed.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
